/**
 * Mock demo dataset — the live source of truth the Zustand store is seeded from.
 *
 * Fully deterministic (fixed ids, dates derived from DEMO_TODAY, no Date.now/random) so
 * server render and client hydration agree. Flags are GENERATED by running the engine over
 * each patient's data as of DEMO_TODAY — never hand-authored — so seeded flags match what
 * the live engine would produce.
 *
 * Cast: one HERO (Maria Reyes, week-10 MTX) plus six supporting patients producing a
 * realistic spread of ~9 open flags across severities. The hero's three-flag flare lands
 * at runtime via the "Simulate hero flare check-in" demo control (see scenarios.ts).
 */

import type {
  CarePlan,
  Channel,
  CheckIn,
  ConstellateData,
  Enrollment,
  Flag,
  ISODate,
  ISODateTime,
  LadderRung,
  Measure,
  Message,
  Patient,
  Provider,
  SymptomKey,
  ThresholdOverrides,
} from "@/lib/types";
import { computeRapid3 } from "@/lib/clinical/rapid3";
import { evaluateCheckin } from "@/lib/engine/evaluateCheckin";
import { evaluateTime } from "@/lib/engine/evaluateTime";
import { dedupeDrafts, flagFromDraft } from "@/lib/flags";
import { addDays } from "@/lib/dates";
import { raMtxProtocol, RA_MTX_PROTOCOL_ID } from "@/lib/mock/protocols";

/** Simulated "today" — anchors every relative date and the time-driven triggers. */
export const DEMO_TODAY: ISODate = "2026-06-24";

export const HERO_PATIENT_ID = "p-maria";

const PROVIDER: Provider = {
  id: "prov-1",
  name: "Dr. Alex Tran",
  role: "Rheumatologist",
};

/** Build an ISO timestamp N days before DEMO_TODAY. */
function at(daysAgo: number, hour = 15): ISODateTime {
  return `${addDays(DEMO_TODAY, -daysAgo)}T${String(hour).padStart(2, "0")}:00:00.000Z`;
}

interface CheckInSpec {
  daysAgo: number;
  channel: Channel;
  functionItems: number[];
  pain: number;
  globalHealth: number;
  symptoms?: SymptomKey[];
  temperatureF?: number;
  note?: string;
}

interface MessageSpec {
  daysAgo: number;
  direction: "inbound" | "outbound";
  channel: Channel;
  body: string;
}

interface PatientSpec {
  id: string;
  name: string;
  age: number;
  sex: "F" | "M";
  phone: string;
  rung: LadderRung;
  cadenceDays: number;
  lastLabDate: ISODate | null;
  nextLabDueDate: ISODate | null;
  nextVisitDate: ISODate | null;
  treatment: string;
  channelPrefs: Channel[];
  thresholds?: ThresholdOverrides;
  checkIns: CheckInSpec[];
  messages?: MessageSpec[];
}

const fill = (v: number) => Array<number>(10).fill(v);

const SPECS: PatientSpec[] = [
  // ───────────── HERO: Maria Reyes — week-10 MTX, stable low, labs due this week ─────────────
  {
    id: HERO_PATIENT_ID,
    name: "Maria Reyes",
    age: 47,
    sex: "F",
    phone: "+1 (555) 014-2231",
    rung: {
      drug: "methotrexate",
      dose: "15 mg weekly",
      startDate: "2026-04-15",
      lastDoseChangeDate: null,
    },
    cadenceDays: 14,
    lastLabDate: "2026-05-15",
    nextLabDueDate: addDays(DEMO_TODAY, 2), // due this week → lab_due flag
    nextVisitDate: "2026-08-05",
    treatment: "MTX 15 mg weekly + folic acid",
    channelPrefs: ["sms", "portal"],
    checkIns: [
      { daysAgo: 24, channel: "sms", functionItems: fill(1), pain: 1, globalHealth: 1 },
      {
        daysAgo: 10,
        channel: "sms",
        functionItems: [1, 1, 1, 1, 1, 1, 1, 1, 1, 0], // FN 3.0
        pain: 1,
        globalHealth: 1,
      },
    ],
    messages: [
      {
        daysAgo: 24,
        direction: "outbound",
        channel: "sms",
        body: "Hi Maria — your first MTX month is going well. Reply to your check-ins anytime.",
      },
      {
        daysAgo: 24,
        direction: "inbound",
        channel: "sms",
        body: "Thanks! Feeling steady so far.",
      },
    ],
  },

  // ───────────── James Okafor — persistent HIGH on MTX 20mg, labs overdue ─────────────
  {
    id: "p-james",
    name: "James Okafor",
    age: 58,
    sex: "M",
    phone: "+1 (555) 027-8810",
    rung: {
      drug: "methotrexate",
      dose: "20 mg weekly",
      startDate: "2026-01-20",
      lastDoseChangeDate: "2026-04-01",
    },
    cadenceDays: 14,
    lastLabDate: "2026-03-20",
    nextLabDueDate: addDays(DEMO_TODAY, -4), // overdue
    nextVisitDate: "2026-07-10",
    treatment: "MTX 20 mg weekly + folic acid",
    channelPrefs: ["portal"],
    checkIns: [
      { daysAgo: 14, channel: "portal", functionItems: fill(2), pain: 4, globalHealth: 3 },
      {
        daysAgo: 3,
        channel: "portal",
        functionItems: [3, 2, 2, 2, 2, 2, 2, 2, 2, 3], // FN 7.3
        pain: 4,
        globalHealth: 3,
      },
    ],
    messages: [
      {
        daysAgo: 3,
        direction: "inbound",
        channel: "portal",
        body: "Still pretty stiff most mornings, not much better.",
      },
    ],
  },

  // ───────────── Priya Shah — recent flare, low → moderate ─────────────
  {
    id: "p-priya",
    name: "Priya Shah",
    age: 39,
    sex: "F",
    phone: "+1 (555) 033-1190",
    rung: {
      drug: "methotrexate",
      dose: "15 mg weekly",
      startDate: "2026-04-01",
      lastDoseChangeDate: null,
    },
    cadenceDays: 14,
    lastLabDate: "2026-05-01",
    nextLabDueDate: "2026-08-01",
    nextVisitDate: "2026-08-20",
    treatment: "MTX 15 mg weekly + folic acid",
    channelPrefs: ["sms", "portal"],
    checkIns: [
      { daysAgo: 16, channel: "sms", functionItems: fill(1), pain: 1, globalHealth: 1 },
      {
        daysAgo: 5,
        channel: "sms",
        functionItems: [2, 1, 1, 1, 1, 1, 1, 1, 1, 2], // FN 4.0
        pain: 2,
        globalHealth: 2,
        symptoms: ["joint_swelling", "morning_stiffness"],
      },
    ],
  },

  // ───────────── Robert Kim — at target, routine quarterly labs due ─────────────
  {
    id: "p-robert",
    name: "Robert Kim",
    age: 64,
    sex: "M",
    phone: "+1 (555) 041-7723",
    rung: {
      drug: "methotrexate",
      dose: "15 mg weekly",
      startDate: "2025-12-01",
      lastDoseChangeDate: "2026-02-01",
    },
    cadenceDays: 21,
    lastLabDate: "2026-03-25",
    nextLabDueDate: addDays(DEMO_TODAY, -1), // due
    nextVisitDate: "2026-09-01",
    treatment: "MTX 15 mg weekly + folic acid",
    channelPrefs: ["portal"],
    checkIns: [
      { daysAgo: 21, channel: "portal", functionItems: fill(1), pain: 0, globalHealth: 0 },
      { daysAgo: 7, channel: "portal", functionItems: fill(1), pain: 0, globalHealth: 0 },
    ],
  },

  // ───────────── Linda Martinez — gone silent (re-engagement) ─────────────
  {
    id: "p-linda",
    name: "Linda Martinez",
    age: 52,
    sex: "F",
    phone: "+1 (555) 055-6642",
    rung: {
      drug: "methotrexate",
      dose: "15 mg weekly",
      startDate: "2026-02-15",
      lastDoseChangeDate: null,
    },
    cadenceDays: 14,
    lastLabDate: "2026-04-10",
    nextLabDueDate: "2026-07-20",
    nextVisitDate: "2026-08-15",
    treatment: "MTX 15 mg weekly + folic acid",
    channelPrefs: ["sms"],
    checkIns: [
      { daysAgo: 46, channel: "sms", functionItems: fill(1), pain: 1, globalHealth: 1 },
      {
        daysAgo: 32,
        channel: "sms",
        functionItems: [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        pain: 1,
        globalHealth: 0,
      },
    ],
    messages: [
      {
        daysAgo: 18,
        direction: "outbound",
        channel: "sms",
        body: "Hi Linda — we haven't heard from you in a couple weeks. Reply STADY to resume check-ins.",
      },
    ],
  },

  // ───────────── David Chen — early MTX, fever + sore throat (red flag), first labs due ─────────────
  {
    id: "p-david",
    name: "David Chen",
    age: 34,
    sex: "M",
    phone: "+1 (555) 062-9081",
    rung: {
      drug: "methotrexate",
      dose: "15 mg weekly",
      startDate: "2026-05-27",
      lastDoseChangeDate: null,
    },
    cadenceDays: 14,
    lastLabDate: null,
    nextLabDueDate: addDays(DEMO_TODAY, 2), // first monthly lab due
    nextVisitDate: "2026-07-25",
    treatment: "MTX 15 mg weekly + folic acid (week 4)",
    channelPrefs: ["sms", "portal"],
    checkIns: [
      {
        daysAgo: 2,
        channel: "sms",
        functionItems: [1, 1, 1, 1, 1, 1, 1, 1, 1, 0], // FN 3.0
        pain: 3,
        globalHealth: 2,
        symptoms: ["fever", "sore_throat", "fatigue"],
        temperatureF: 101.2,
        note: "Sore throat since yesterday, feeling feverish.",
      },
    ],
    messages: [
      {
        daysAgo: 2,
        direction: "inbound",
        channel: "sms",
        body: "Throat's been sore and I feel warm. Should I take my dose tomorrow?",
      },
    ],
  },

  // ───────────── Susan Patel — MTX failure → biologic added, recent flare ─────────────
  {
    id: "p-susan",
    name: "Susan Patel",
    age: 45,
    sex: "F",
    phone: "+1 (555) 078-3345",
    rung: {
      drug: "adalimumab",
      dose: "40 mg every 2 weeks",
      startDate: "2026-03-10",
      lastDoseChangeDate: "2026-03-10",
    },
    cadenceDays: 14,
    lastLabDate: "2026-03-15",
    nextLabDueDate: null, // biologic — not on the csDMARD lab rule
    nextVisitDate: "2026-07-30",
    treatment: "Adalimumab 40 mg q2w + MTX 15 mg weekly",
    channelPrefs: ["portal"],
    checkIns: [
      { daysAgo: 18, channel: "portal", functionItems: fill(1), pain: 2, globalHealth: 0 },
      {
        daysAgo: 6,
        channel: "portal",
        functionItems: [2, 1, 1, 1, 1, 1, 1, 1, 1, 2], // FN 4.0
        pain: 2,
        globalHealth: 2,
        symptoms: ["joint_swelling"],
      },
    ],
  },
];

function carePlanIdFor(patientId: string): string {
  return `cp-${patientId.replace(/^p-/, "")}`;
}

export function buildSeed(): ConstellateData {
  const protocol = raMtxProtocol();

  const patients: Patient[] = [];
  const enrollments: Enrollment[] = [];
  const carePlans: CarePlan[] = [];
  const checkIns: CheckIn[] = [];
  const messages: Message[] = [];
  const flags: Flag[] = [];

  for (const spec of SPECS) {
    const carePlanId = carePlanIdFor(spec.id);
    const enrollmentId = `en-${spec.id.replace(/^p-/, "")}`;

    const patient: Patient = {
      id: spec.id,
      name: spec.name,
      age: spec.age,
      sex: spec.sex,
      phone: spec.phone,
      conditions: ["RA"],
      enrollmentId,
      carePlanId,
    };

    const enrollment: Enrollment = {
      id: enrollmentId,
      patientId: spec.id,
      protocolId: RA_MTX_PROTOCOL_ID,
      consentAt: at(60),
      phone: spec.phone,
      conditions: ["RA"],
      treatment: spec.treatment,
      channelPrefs: spec.channelPrefs,
    };

    const carePlan: CarePlan = {
      id: carePlanId,
      patientId: spec.id,
      protocolId: RA_MTX_PROTOCOL_ID,
      target: "low",
      currentRung: spec.rung,
      cadenceDays: spec.cadenceDays,
      thresholds: spec.thresholds ?? {},
      nextLabDueDate: spec.nextLabDueDate,
      lastLabDate: spec.lastLabDate,
      nextVisitDate: spec.nextVisitDate,
    };

    // Build check-ins (+ their RAPID3 measures), oldest first.
    const patientCheckIns: CheckIn[] = spec.checkIns
      .slice()
      .sort((a, b) => b.daysAgo - a.daysAgo)
      .map((c, i) => {
        const id = `ci-${spec.id}-${i}`;
        const createdAt = at(c.daysAgo);
        const r = computeRapid3({
          functionItems: c.functionItems,
          pain: c.pain,
          globalHealth: c.globalHealth,
        });
        const measure: Measure = {
          id: `m-${id}`,
          checkInId: id,
          type: "RAPID3",
          value: r.value,
          components: r.components,
          bucket: r.bucket,
          createdAt,
        };
        return {
          id,
          patientId: spec.id,
          carePlanId,
          channel: c.channel,
          createdAt,
          answers: {
            rapid3: {
              functionItems: c.functionItems,
              pain: c.pain,
              globalHealth: c.globalHealth,
            },
            symptoms: {
              symptoms: c.symptoms ?? [],
              temperatureF: c.temperatureF,
              note: c.note,
            },
          },
          measures: [measure],
          status: "processed",
        } satisfies CheckIn;
      });

    // Messages
    const patientMessages: Message[] = (spec.messages ?? []).map((m, i) => ({
      id: `msg-${spec.id}-${i}`,
      patientId: spec.id,
      channel: m.channel,
      direction: m.direction,
      body: m.body,
      createdAt: at(m.daysAgo, 12 + i),
    }));

    // ── Generate this patient's open flags by running the engine ──
    const drafts = [];
    const latest = patientCheckIns.at(-1) ?? null;
    if (latest) {
      const measure = latest.measures[0];
      const previousMeasure =
        patientCheckIns.length > 1
          ? patientCheckIns[patientCheckIns.length - 2].measures[0]
          : null;
      drafts.push(
        ...evaluateCheckin({
          checkIn: latest,
          measure,
          previousMeasure,
          carePlan,
          protocol,
          patient,
        }),
      );
    }
    drafts.push(
      ...evaluateTime({
        carePlan,
        protocol,
        patient,
        asOf: DEMO_TODAY,
        lastCheckinAt: latest?.createdAt ?? null,
        latestBucket: latest?.measures[0].bucket,
      }),
    );

    for (const draft of dedupeDrafts([], drafts)) {
      const createdAt = draft.kind === "checkin" ? (latest?.createdAt ?? at(1)) : at(1, 9);
      flags.push(
        flagFromDraft(
          draft,
          `flag-${spec.id}-${draft.triggerId}`,
          createdAt,
          "open",
        ),
      );
    }

    patients.push(patient);
    enrollments.push(enrollment);
    carePlans.push(carePlan);
    checkIns.push(...patientCheckIns);
    messages.push(...patientMessages);
  }

  return {
    provider: PROVIDER,
    protocols: [protocol],
    patients,
    enrollments,
    carePlans,
    checkIns,
    messages,
    flags,
    actions: [],
    asOf: DEMO_TODAY,
  };
}
